import java.sql.*;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class CreateDatabases extends javax.swing.JFrame {

    /**
     * Creates new form CreateDatabases
     */
    public CreateDatabases() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Create");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try
        {
        Class.forName("java.sql.DriverManager");
        Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/","root","root");
        Statement stmt=(Statement)con.createStatement();
        String sql1="Create database E_AUCTION;";
        stmt.executeUpdate(sql1);
        String sql2="Use E_AUCTION;";
        stmt.executeUpdate(sql2);
        String sql3="Create table Users(Name varchar(15),UserName varchar(20) primary key,Password varchar(15),PhoneNo varchar(12),City varchar(20),CardNo varchar(20));";
        stmt.executeUpdate(sql3);
        String sql4="Create table BMW_bid(Name varchar(15),UserName varchar(20),PhoneNo varchar(12),City varchar(20),BidAmount int(20) primary key);";
        stmt.executeUpdate(sql4);
        String sql5="Create table SKODA_bid(Name varchar(15),UserName varchar(20),PhoneNo varchar(12),City varchar(20),BidAmount int(20) primary key);";
        stmt.executeUpdate(sql5);
        String sql6="Create table DUKE_bid(Name varchar(15),UserName varchar(20),PhoneNo varchar(12),City varchar(20),BidAmount int(20) primary key);";
        stmt.executeUpdate(sql6);
        String sql7="Create table YAMAHA_bid(Name varchar(15),UserName varchar(20),PhoneNo varchar(12),City varchar(20),BidAmount int(20) primary key);";
        stmt.executeUpdate(sql7);
        String sql8="Create table ROLEX_bid(Name varchar(15),UserName varchar(20),PhoneNo varchar(12),City varchar(20),BidAmount int(20) primary key);";
        stmt.executeUpdate(sql8);
        JOptionPane.showMessageDialog(this,"DATABASE AND TABLES CREATED SUCCESSFULLY");
        this.setVisible(false);
        new Welcome_Frame().setVisible(true);
        }
        catch(Exception e)
                {
                JOptionPane.showMessageDialog(this,e.getMessage());
                }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateDatabases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateDatabases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateDatabases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateDatabases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateDatabases().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
